name: Pure Android APK Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # রান টাইমে অটোমেটিক গ্রেডল ফাইল তৈরি এবং বিল্ড প্রসেস
      - name: Auto Initialize Gradle and Build
        run: |
          gradle init --type basic --dsl groovy
          gradle wrapper --gradle-version 8.4
          chmod +x gradlew
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: "**/build/outputs/apk/debug/*.apk"
