name: Pure Android APK Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build APK
        run: |
          wget https://github.com -O gradle/wrapper/gradle-wrapper.jar
          bash gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: "**/build/outputs/apk/debug/*.apk"
